# Generated by Django 4.1.3 on 2023-12-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0004_alter_song_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songgenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='song',
            new_name='song_id',
        ),
    ]
